name: Discover the Perfect Wealth System
favicon: null
layout_spectrum: 0.40645906794816256
typography_spectrum: 0.12080362881533802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.28295407234691083
  lightness: 0.26438435376621783
  saturation: 0.9809602492023259
  rhythmicContrast: 0.10154490754939616
purpose: []
