name: Discover the Perfect Wealth System
favicon: null
layout_spectrum: 0.02537
typography_spectrum: 0.12080362881533802
title: The Possibilities are Endless
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4ed'
    - '#517beb'
    - '#9ecbf4'
    - '#374123'
    - '#69972a'
  brandStrength: 0
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0
purpose: []
